### ISSUE TITLE
Performance issues on medium-sized shaders (> 500+ line of code)

### ISSUE THREAD

**Issue by alienself** [brendan-duncan/wgsl_reflect#49]
Hi again!

I wanted to report an issue that I am having with the library: 

it's quite slow specially for shader > 500 lines of code (not huge but just a bit longer). 

For instance, my PBR / physical shader is about 1000 lines of WGSL code and the reflection takes 200ms on a beefy desktop machine. 
Note that it then takes 20ms to compile the WGSL shader itself (for comparison).

Simply put: is there anything we could do to speed up the reflection?

The problem of the web and non-binary shaders is that we must recompile and reflect our shaders are runtime on the fly 
since compiling all shader variants right from the start of the app would dramatically slow down the start time.

But waiting 200ms for a simple PBR shader variant to be reflected is a tough pile to swallow, specially if it happens often :(

Do you have any tips to mitigate this?
Would the reflection be faster if function bodies would be empty for instance?

**Comment by brendan-duncan** [comment]
Not much I can do about that, other than work on optimizing the parsing. I haven't spent much time on optimizations yet, I suspect most of the time is probably spent in the lexer doing keyword lookups. I'll take a look at seeing if I can improve things soon.

**Comment by brendan-duncan** [comment]
Taking a quick look at the scanner code of the parser...there is a **lot** of room for improvement. For every character that gets scanned, it's checking against all keywords and tokens. I should be able to get the parsing time down considerably cleaning up that code. I'll try and get to that soon.

**Comment by brendan-duncan** [comment]
Even without doing a full optimization pass, a quick update got the parsing time of a 1k shader from ~200ms to ~38ms for me. I'll clean that up and at least get that update pushed for now. There's still room for further improvement, but that's not too bad for a 10 minute "let me take a quick look at that".

**Comment by brendan-duncan** [comment]
I pushed the optimizations to git for fixing up the keyword lookup in the scanner. The ~700 line shader I timed took about 22ms. A lot better than it was.

**Comment by alienself** [comment]
Wow! Thank you very much Brendan! You are amazing!! I got the same performance boost on my side for a 1k PBR shader from 200ms to ~40ms. Do you think that it would be possible to squeeze even more performance out of it?

**Comment by brendan-duncan** [comment]
I believe so, but can't say by how much until I get the chance to do it.

It currently scans one character at a time and checks the accumulated characters to see if they match one of the keywords or token types. I can have it make certain assumptions when scanning to reduce the number of times it has to check the token rules. For example, if it's an alpha-numeric character, it can continue scanning alpha-numeric characters until it reaches a character that is not one, then it can test that whole word, instead of testing each character. It should reduce a significant percentage of the token rule tests. But now that the token rule checks are faster, Shouldn't take much to add that optimization, hopefully I can get to it soon.

**Comment by brendan-duncan** [comment]
I added a couple more optimizations to the scanner. It will first early-out check simple token types (like ";", "{", "}", etc). Then if the character is an alpha or "_" it will add any subsequent alpha-numeric-underscore characters, and then do a quick check if it's a keyword, otherwise it's an identifier. If those checks don't pass, it will continue to do the regular scanning, which is a bit heavier since it has to resolve a few syntax ambiguities.

I tested a 1500 line shader. 
Before the new optimizations it took ~26ms to parse.
After the new optimizations, it took ~12ms to parse.

A far cry from the 200ms it started with. I suppose I should have paid attention to performance sooner, I'm glad there were some simple optimization with big benefits.

**Comment by alienself** [comment]
Incredible! That is honestly game changer, completely night and day on large shaders! Hats off!

Thank you so much for this massive performance improvement, this is a truly great contribution to the WebGPU / WGSL ecosystem and I am sure this will help many adopt the new shading language in their projects.
